### ISSUE TITLE
add scripts to aseprite website

### ISSUE THREAD

**Issue by pixelartgirl** [behreajj/AsepriteAddons#1]
Hi

Those scripts for aseprite are great!
Maybe you should ask if they add a link on the aseprite website/github to your github?

They are collecting translation extensions too on their github. I think they should do the same with lua scripts.
I'm doing the Dutch translation now.

PixelArtGirl

**Comment by behreajj** [comment]
Hi @pixelartgirl ,

Thanks! I hope the scripts continue to be useful to you.

Hmm, there's an [Aseprite Scripts Collection](https://community.aseprite.org/t/aseprite-scripts-collection/3599) thread on the Community Forum with a lot of great scripts on it. I don't know, maybe there could be a section on the [tutorials](https://www.aseprite.org/docs/tutorial) page or the [scripting](https://www.aseprite.org/docs/scripting) page? Looks like the Github repo for the web page is https://github.com/aseprite/docs .

Good luck on your Dutch translation!

Jeremy
