### ISSUE TITLE
LCH Picker: field "canvas" does not exist

### ISSUE THREAD

**Issue by sylv256** [behreajj/AsepriteAddons#29]
**Operating System**
Linux 5.15.0-69-generic; Ubuntu 20.04

**Aseprite version**
`1.2.40-x64` (Steam)

**Sprite color mode**
RGB

**Current behavior**
When the `dialogs/color/lchPicker` script is selected, an error pops in the console.

**To Reproduce**
Select the `dialogs/color/lchPicker` script.

**Expected behavior**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/18603248/235046561-320674bf-532f-4c8e-8052-6cd9514e27dc.png)

**Comment by behreajj** [comment]
Hi SylvKT,

Aseprite version 1.3-rc2 is the minimum version to use for recent updates to these scripts. That's the version which [supports](https://github.com/aseprite/api/blob/main/Changes.md) dialog canvases. You can either switch to the last 1.2.40 supported commit for these scripts, [092c0c19fd](https://github.com/behreajj/AsepriteAddons/tree/092c0c19fd519b456eaf3f837941a4fd9c9dfd77), or switch to the beta branch of Aseprite. There's an animated image that shows how to switch Aseprite version on Steam [here](https://aseprite.org/beta).

**Comment by sylv256** [comment]
Thank you!
